
spring:
  devtools:
    restart:
      enabled: true #热部署生效
      additional-paths: src/main/java #设置重启的目录,添加那个目录的文件需要restart
      exclude: WEB-INF/**
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yunmenglake?allowMultiQueries=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
